export const Config = {
  //DELAY WILL BE RANDOMIZE BETWEEN MIN AND MAX
  DELAYMININMINUTES: 240,
  DELAYMAXINMINUTES: 480,

  // ================
  // SEASON 1
  // ================
  //TRANSACTION AMOUNT WILL BE RANDOMIZE BETWEEN MIN AND MAX
  TXAMOUNTMIN: 0.0000001,
  TXAMOUNTMAX: 0.000001,

  //TRANSFER TO YOUR OWN ADDRESS
  USESELFTRANSFER: false,
  SELFTRANSFERCOUNT: 10,

  //TRANSFER TO ADDRESS ON THIS LIST IF EMPTY -> SKIP
  USEFRIENDTRANSFER: false,
  FRIENDTRANSFERLIST: [],

  //SWAP TOKEN (ZENITHSWAP , FAROSWAP)
  USESWAP: false,
  SWAPCOUNT: 10,

  //ADD LIQUIDITY (SENITHSWAP, FAROSWAP)
  USEADDLIQUIDITY: false,
  ADDLIQUIDITYCOUNT: 10,

  // ================
  // SEASON 2
  // ================

  //PRIMUS TRANSFER TO RANDOM TWITTER LIST
  USEPRIMUSTRANSFER: true,
  PRIMUSTRANSFERCOUNT: 10,
  PRIMUSTRANSFERLIST: ["WidiSkel"],

  //AQUAFLUX CRAFTING
  USEAQUAFLUXCRAFT: true,
  AQUAFLUXCRAFTCOUNT: 9,

  //OPENFI SUPPLY AND BORROW
  USEOPENFI: true,
  OPENFISUPPLYCOUNT: 10,

  //OPENFI SUPPLY AND BORROW
  USEAUTOSTAKING: true,
  AUTOSTAKINGCOUNT: 10,

  //NOTE : Every count is daily based
  //so when you already reach the count, bot will run on continues cooldown until next day and daily count reset.
};
